### ISSUE TITLE
License

### ISSUE THREAD

**Issue by thorade** [xie-dongping/modparc#54]
Currently, there is a LICENSE file and a COPYING file, that seems to be redundant; the COPYING file can probably be deleted (github is looking for a LICENSE file first).

Additionally, the license text seems to be slightly changed, otherwise github would recognize what license is used and display it in the overview (next to the number of contributors):
https://github.com/blog/2252-license-now-displayed-on-repository-overview
https://github.com/blog/2335-open-source-license-descriptions-and-metadata
To fix this, I would recommend deleting both files LICENSE and COPYING and then recreate the LICENSE file using githubs webinterface `Create new file`. When you name the new files LICENSE, a dropdown menu appears on the right.

**Comment by xie-dongping** [comment]
Thanks for the  hints. I tried to add the `COPYING` file because I want github to display it. 

I would try it you way.
